VetPet/Controllers/SedeClinicaController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using VetPet.Database.VetContext;
using VetPet.Models;

namespace VetPet.Controllers
{
    public class SedeClinicaController : Controller
    {
        private readonly VetContext _context;


        public SedeClinicaController (VetContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var sedeclinica = _context.SedeClinica.ToList();
            return View(sedeclinica);
        }

        public IActionResult Create() 
        {
            return View();
        }

        // CREAR SEDE CLINICA
        [HttpPost]
        public IActionResult Create(SedeClinicaEntity model) 
        {
            if (ModelState.IsValid)
            {
                var sedeclinica = new SedeClinicaEntity
                {
                    Nombre = model.Nombre,
                    Direccion = model.Direccion,    
                };

                _context.SedeClinica.Add(sedeclinica);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }


            return View(model);
        }

        // EDITAR SEDE CLINICA

        [HttpGet]
        public IActionResult Edit(int id)
        {

            var sedeclinica = _context.SedeClinica.FirstOrDefault(a => a.Id == id);

            if (sedeclinica == null)
            {
                return NotFound();
            }

            return View(sedeclinica);
        }

        [HttpPost]
        public IActionResult Edit(SedeClinicaEntity model)
        {
            if (ModelState.IsValid) {

                var sedeclinica = _context.SedeClinica.FirstOrDefault(a =>a.Id == model.Id);

                if (sedeclinica == null)
            {
                return NotFound();
            }

            sedeclinica.Nombre = model.Nombre;
            sedeclinica.Direccion = model.Direccion;
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(model);

        }

        // BORRAR SEDE CLINICA
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var sedeclinica = _context.SedeClinica.FirstOrDefault(a => a.Id == id);

            if (sedeclinica == null)
            {
                return NotFound();
            }

            return View(sedeclinica);
        }

        [HttpPost]
        public IActionResult ConfirmedDelete(int id)
        {

            var sedeclinica = _context.SedeClinica.FirstOrDefault(a => a.Id == id);

            if (sedeclinica == null)
            {
                return NotFound();
            }


            _context.SedeClinica.Remove(sedeclinica);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

VetPet/Views/SedeClinica/Create.cshtml
@model VetPet.Models.SedeClinicaEntity

<h2>Crear Nueva Sede</h2>

<form asp-action="Create" method="post">
    <div class="form-group col-md-4">
        <label asp-for="Nombre">Nombre</label>
        <input asp-for="Nombre" class="form-control" placeholder="Nombre" required>
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="form-group col-md-4">
        <label asp-for="Direccion">Direccion</label>
        <input asp-for="Direccion" class="form-control" placeholder="Direccion" required>
        <span asp-validation-for="Direccion" class="text-danger"></span>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-success">Guardar</button>
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

VetPet/Views/SedeClinica/Delete.cshtml
@model VetPet.Models.SedeClinicaEntity

<h2>Confirmar Eliminación</h2>

<p>¿Estás seguro de que quieres borrar la siguiente sede?</p>
<p><strong>@Model.Nombre </strong></p>
<p><strong>@Model.Direccion </strong></p>

<form asp-action="ConfirmedDelete">
    <input type="hidden" asp-for="Id" />

    <button type="submit" class="btn btn-danger">Sí, Borrar</button>
    <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
</form>

VetPet/Views/SedeClinica/Edit.cshtml
@model VetPet.Models.SedeClinicaEntity

<h2>Editar Sede</h2>

<form asp-action="Edit">
    <input type="hidden" asp-for="Id" />

    <div class="form-group col-md-4">
        <label asp-for="Nombre">Nombre</label>
        <input asp-for="Nombre" class="form-control" required>
    </div>

    <div class="form-group col-md-4">
        <label asp-for="Direccion">Direccion</label>
        <input asp-for="Direccion" class="form-control" required>
    </div>

    <div class="form-group" method="post">
        <button type="submit" class="btn btn-info">Guardar Cambios</button>
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

VetPet/Views/SedeClinica/Index.cshtml
@model List<VetPet.Models.SedeClinicaEntity>

<h2 class="titulo">Mantenimiento de sedes</h2>

<div class="crearnuevo">
    <a asp-controller="SedeClinica" asp-action="Create" class="btn btn-primary">Crear Nueva</a>
</div>

<div class="table-container">
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Direccion</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var sedeclinica in Model)
            {
                <tr>
                    <td>@sedeclinica.Id</td>
                    <td>@sedeclinica.Direccion</td>
                    <td>
                        <a asp-controller="SedeClinica" asp-action="Edit" asp-route-id="@sedeclinica.Id" class="btn btn-info btn-sm crud-button">Editar</a>
                    </td>
                    <td>
                        <a asp-controller="SedeClinica" asp-action="Delete" asp-route-id="@sedeclinica.Id" class="btn btn-danger btn-sm crud-button">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<style>
    .titulo {
        text-align: center;
        color: blue;
        margin-bottom: 20px;
    }

    .crearnuevo {
        text-align: left;
        margin-bottom: 10px;
    }

    .crud-button {
        margin-left: 5px;
    }
</style>