VetPet/Controllers/EnfermedadesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using VetPet.Database.VetContext;
using VetPet.Models;

namespace VetPet.Controllers
{
    public class EnfermedadesController : Controller
    {
        private readonly VetContext _context;

        public EnfermedadesController(VetContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            var enfermedades = _context.Enfermedades.ToList();
            return View(enfermedades);
        }


        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EnfermedadesEntity model)
        {
            if (ModelState.IsValid)
            {
                var enfermedad = new EnfermedadesEntity
                {
                    DescripcionEnferm = model.DescripcionEnferm,
                };

                _context.Enfermedades.Add(enfermedad);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }


            return View(model);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            var enfermedad = _context.Enfermedades.FirstOrDefault(a => a.Id == id);

            if (enfermedad == null)
            {
                return NotFound();
            }

            return View(enfermedad);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EnfermedadesEntity model)
        {
            if (ModelState.IsValid)
            {
                var enfermedad = _context.Enfermedades.FirstOrDefault(a => a.Id == model.Id);

                if (enfermedad == null)
                {
                    return NotFound();
                }


                enfermedad.DescripcionEnferm = model.DescripcionEnferm;

                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var enfermedad = _context.Enfermedades.FirstOrDefault(a => a.Id == id);

            if (enfermedad == null)
            {
                return NotFound();
            }

            return View(enfermedad);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmedDelete(int id)
        {

            var enfermedad = _context.Enfermedades.FirstOrDefault(a => a.Id == id);

            if (enfermedad == null)
            {
                return NotFound();
            }


            _context.Enfermedades.Remove(enfermedad);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

VetPet/Views/Enfermedades/Create.cshtml
@model VetPet.Models.EnfermedadesEntity

<h2>Crear Nueva Enfermedades</h2>

<form asp-action="Create" method="post">
    <div class="form-group col-md-4">
        <label asp-for="DescripcionEnferm">Descripcion</label>
        <input asp-for="DescripcionEnferm" class="form-control" placeholder="Descripcion" required>
        <span asp-validation-for="DescripcionEnferm" class="text-danger"></span>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-success">Guardar</button>
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

VetPet/Views/Enfermedades/Delete.cshtml
@model VetPet.Models.EnfermedadesEntity

<h2>Confirmar Eliminación</h2>

<p>¿Estás seguro de que quieres borrar la siguiente enfermedad?</p>
<p><strong>@Model.DescripcionEnferm </strong></p>

<form asp-action="ConfirmedDelete">
    <input type="hidden" asp-for="Id" />
    
    <button type="submit" class="btn btn-danger">Sí, Borrar</button>
    <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
</form>

VetPet/Views/Enfermedades/Edit.cshtml
@model VetPet.Models.EnfermedadesEntity

<h2>Editar Enfermedad</h2>

<form asp-action="Edit">
    <input type="hidden" asp-for="Id" />

    <div class="form-group col-md-4">
        <label asp-for="DescripcionEnferm">Descripcion</label>
        <input asp-for="DescripcionEnferm" class="form-control" required>
    </div>


    <div class="form-group" method="post">
        <button type="submit" class="btn btn-info">Guardar Cambios</button>
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

VetPet/Views/Enfermedades/Index.cshtml
@model List<VetPet.Models.EnfermedadesEntity>

<h2 class="titulo">Mantenimiento de Enfermedades</h2>

<div class="crearnuevo">
    <a asp-controller="Enfermedades" asp-action="Create" class="btn btn-primary">Crear Nueva</a>
</div>

<div class="table-container">
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Descripción</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var enfermedades in Model)
            {
                <tr>
                    <td>@enfermedades.Id</td>
                    <td>@enfermedades.DescripcionEnferm</td>
                    <td>
                        <a asp-controller="Enfermedades" asp-action="Edit" asp-route-id="@enfermedades.Id" class="btn btn-info btn-sm crud-button">Editar</a>
                    </td>
                    <td>
                        <a asp-controller="Enfermedades" asp-action="Delete" asp-route-id="@enfermedades.Id" class="btn btn-danger btn-sm crud-button">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<style>
    .titulo {
        text-align: center;
        color: blue;
        margin-bottom: 20px;
    }

    .crearnuevo {
        text-align: left;
        margin-bottom: 10px;
    }

    .crud-button {
        margin-left: 5px;
    }
</style>